version: '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'queue-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=queue_db'

  app:
    build: ./
    container_name: 'queue-app'
    ports:
      - "8080:8080"